name: First Demo Task

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List and Read File
        run: |
          echo "Welcome to GitHub Actions"
          ls -ltra
          cat README.md
