name: Generate Ascii Workflow - Multiple Jobs
on: push
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
    #   - name: Checkout Repo
    #     uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAAAAR" >> dragon.txt
      - name: Upload File
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
        

  test_job:
    runs-on: ubuntu-latest
    needs: build_job
    steps:
      - name: Download File
        uses: actions/download-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
      - name: Test File Exists
        run: grep -i "dragon" ./dragon.txt

  deploy_job:
    runs-on: ubuntu-latest
    needs: test_job
    steps:
      - name: Download File
        uses: actions/download-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
      - name: Read File
        run: cat ./dragon.txt
      - name: Checkout Repo Files
        run: ls -ltra
      - name: Deploy
        run: echo "Deploying the application..."