name: Matrix Configuration
on:
  push: 
  workflow_dispatch: 

jobs:
  matrix-configuration-deploy-on-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest]
        image: [hello-world, alpine, nginx]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Image on ${{ matrix.os }} with ${{ matrix.image }}
        run: docker run ${{ matrix.image }}

#   matrix-configuration-deploy-on-windows:
#     runs-on: windows-latest
#     steps:
#       - name: Echo Docker Details
#         run: docker info

#       - name: Run Images
#         run: docker run hello-world
  