name: Exploring Variables and Secrets
on:
  push:
env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx
    DOCKER_USERNAME: eljohns

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build  
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}/$IMAGE_NAME:latest .

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo docker login -u ${{ env.DOCKER_USERNAME }} -p ${{ env.DOCKER_PASSWORD }} 

      - name: Docker Publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/$IMAGE_NAME:latest
        
    
        