name: Exploring Variables and Secrets
on:
#   push:
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Set the logging level'
        required: true
        default: 'warning'
        type: choice
        options:
          - debug
          - info
          - warning
          - error
          - critical
env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build  
        run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}/$IMAGE_NAME:latest .

      - name: Docker Login
        # Using secrets to store sensitive information
        # DOCKER_USERNAME and DOCKER_PASSWORD are set in the repository settings
        # Secrets are not available in the workflow file, but can be accessed using ${{ secrets.SECRET_NAME }}
        run: echo docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

      - name: Docker Publish
        run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    concurrency: 
      group: deploy-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Docker Run
        run: |
          echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          sleep 120s
        
    
        